- type: gameMapPool
  id: CorvaxDefaultMapPool
  maps:
  # Highpop
  - CorvaxDelta
  - CorvaxAvrite
  - CorvaxAstra
  - CorvaxPilgrim
  - CorvaxGlacier
  - Box
  # Midpop
  - CorvaxPaper
  #- CorvaxPearl — До реворка
  - CorvaxOutpost
  - CorvaxAwesome
  - Bagel
  - Marathon
  #- Train — До реворка оффами
  # Lowpop
  - CorvaxSilly
  - CorvaxMaus
  - CorvaxTushkan
  - Packed
  - Omega
